"""auth_hardening_and_employee_user_link

Revision ID: d5066f5bc143
Revises: a8a79b45dbd9
Create Date: 2026-10-04 12:12:40.280061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5066f5bc143'
down_revision: Union[str, Sequence[str], None] = 'a8a79b45dbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False, comment='Unique JWT ID of the revoked token'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK reference to the user the token was issued to'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Original expiry of the token; row is safe to delete after this'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.add_column('employees', sa.Column('user_id', sa.UUID(), nullable=True, comment='FK to the login account owned by this employee (self-service access)'))
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_foreign_key('fk_employees_user_id_users', 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False, comment='Consecutive failed login attempts since the last successful login'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Login is refused until this timestamp after too many failed attempts'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_constraint('fk_employees_user_id_users', 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_column('employees', 'user_id')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
