"""initial_database_schema

Revision ID: e09a9f3748cc
Revises: 
Create Date: 2026-07-31 11:24:45.425668

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e09a9f3748cc'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('model_name', sa.String(length=255), nullable=False, comment='Descriptive name of the ML model'),
    sa.Column('model_version', sa.String(length=50), nullable=False, comment='Semantic version of the model (e.g. v1.0.0)'),
    sa.Column('algorithm', sa.String(length=100), nullable=False, comment='The algorithm used to train the model (e.g., Random Forest)'),
    sa.Column('training_dataset', sa.String(length=255), nullable=False, comment='Reference or name of the dataset used for training'),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=False, comment='Model evaluation accuracy score percentage'),
    sa.Column('precision_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Model evaluation precision score percentage'),
    sa.Column('recall_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Model evaluation recall score percentage'),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Model evaluation F1 score percentage'),
    sa.Column('model_file_path', sa.String(length=500), nullable=True, comment='File path or URI where the serialized model binary is stored'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates whether this model version is active for inference'),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this model version was set active/deployed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_algorithm'), 'model_registry', ['algorithm'], unique=False)
    op.create_index(op.f('ix_model_registry_is_active'), 'model_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_registry_model_version'), 'model_registry', ['model_version'], unique=True)
    op.create_table('skills',
    sa.Column('skill_code', sa.String(length=50), nullable=False, comment='Unique identifier code for the skill (e.g., SK-PY-01)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique descriptive name of the skill'),
    sa.Column('skill_category', sa.String(length=100), nullable=False, comment='Category of the skill (e.g., Technical, Soft, Domain)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what the skill encompasses'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Sort order for displaying skills on front-end interfaces'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates whether the skill is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_skill_code'), 'skills', ['skill_code'], unique=True)
    op.create_table('training_courses',
    sa.Column('course_code', sa.String(length=50), nullable=False, comment='Unique identifier code for the course (e.g. TR-SEC-01)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Course name or title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the course contents and objectives'),
    sa.Column('provider', sa.String(length=255), nullable=False, comment='Company or platform offering the training (e.g. Udemy, Pluralsight, Internal)'),
    sa.Column('duration_hours', sa.Numeric(precision=5, scale=2), nullable=False, comment='Course duration in hours'),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty_level'), nullable=False, comment='Intended skill difficulty level (e.g. BEGINNER, ADVANCED)'),
    sa.Column('training_mode', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='training_mode'), nullable=False, comment='Training delivery mode (e.g. ONLINE, OFFLINE, HYBRID)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates whether the course is open for new enrollments'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_courses_course_code'), 'training_courses', ['course_code'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username for the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address for the user'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password for authentication'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='Optional user-facing display name'),
    sa.Column('role', sa.Enum('HR_ADMIN', 'HR_MANAGER', 'EMPLOYEE', name='user_role'), nullable=False, comment='Role determining permissions within the application'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the user account is active'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment="Timestamp of the user's last successful login"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='FK reference to the User performing the action (nullable for system events)'),
    sa.Column('entity_name', sa.String(length=100), nullable=False, comment='Name of the affected entity/table (e.g. Employee, User)'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='Primary key ID of the affected entity record'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='The action performed (e.g. CREATE, UPDATE, DELETE, LOGIN)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description of the log entry'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address from which the action was initiated (supports IPv4 and IPv6)'),
    sa.Column('created_at_audit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the action occurred'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at_audit'), 'audit_logs', ['created_at_audit'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_code', sa.String(length=20), nullable=False, comment='Unique shorthand identifier for the department (e.g. ENG, HR)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique full name of the department'),
    sa.Column('description', sa.Text(), nullable=True, comment="Detailed description of department's purpose"),
    sa.Column('hr_manager_user_id', sa.UUID(), nullable=True, comment='FK reference to the User serving as HR Manager'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the department is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['hr_manager_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_department_code'), 'departments', ['department_code'], unique=True)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK reference to the User receiving the notification'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short header title of the notification'),
    sa.Column('message', sa.Text(), nullable=False, comment='Full text message of the notification'),
    sa.Column('notification_type', sa.Enum('SYSTEM', 'ALERT', 'REMINDER', 'AI_RECOMMENDATION', name='notification_type'), nullable=False, comment='Type of notification (e.g. SYSTEM, ALERT, AI_RECOMMENDATION)'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Indicates whether the notification has been read'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the notification was marked read'),
    sa.Column('created_at_notification', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the notification was created'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('training_skills',
    sa.Column('training_course_id', sa.UUID(), nullable=False, comment='FK reference to the TrainingCourse'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='FK reference to the Skill'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_course_id'], ['training_courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_course_id', 'skill_id', name='uq_training_skills_course_skill')
    )
    op.create_index(op.f('ix_training_skills_skill_id'), 'training_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_training_skills_training_course_id'), 'training_skills', ['training_course_id'], unique=False)
    op.create_table('job_roles',
    sa.Column('department_id', sa.UUID(), nullable=False, comment='FK reference to the Department this job role belongs to'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Title of the job role (e.g. Software Engineer, Tech Lead)'),
    sa.Column('grade_level', sa.Integer(), nullable=False, comment='Pay or seniority grade level (e.g. 1 to 10)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed job description and responsibilities'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the job role is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'title', name='uq_job_roles_department_title')
    )
    op.create_index('ix_job_roles_department_grade', 'job_roles', ['department_id', 'grade_level'], unique=False)
    op.create_index(op.f('ix_job_roles_department_id'), 'job_roles', ['department_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=50), nullable=False, comment='Unique employee code assigned by the organization'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment="Employee's first name"),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment="Employee's last name"),
    sa.Column('date_of_birth', sa.Date(), nullable=False, comment="Employee's date of birth"),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=False, comment="Employee's gender identity"),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Primary contact phone number'),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True, comment='Optional secondary phone number'),
    sa.Column('personal_email', sa.String(length=255), nullable=True, comment="Employee's personal email address"),
    sa.Column('official_email', sa.String(length=255), nullable=False, comment="Employee's company-issued email address"),
    sa.Column('department_id', sa.UUID(), nullable=False, comment="FK reference to the employee's department"),
    sa.Column('job_role_id', sa.UUID(), nullable=False, comment="FK reference to the employee's job role"),
    sa.Column('manager_id', sa.UUID(), nullable=True, comment="FK reference to the employee's manager (self-reference)"),
    sa.Column('date_of_joining', sa.Date(), nullable=False, comment='Date when the employee joined the company'),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'TERMINATED', 'ON_LEAVE', 'SUSPENDED', name='employment_status'), nullable=False, comment='Current employment status of the employee'),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='employment_type'), nullable=False, comment='Contract type (e.g. FULL_TIME, CONTRACT)'),
    sa.Column('work_mode', sa.Enum('OFFICE', 'REMOTE', 'HYBRID', name='work_mode'), nullable=False, comment='Work setting (e.g. OFFICE, REMOTE)'),
    sa.Column('work_location', sa.String(length=255), nullable=False, comment='Specific geographic office or location'),
    sa.Column('profile_photo_url', sa.String(length=512), nullable=True, comment="URL link to the employee's profile picture"),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_job_role_id'), 'employees', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_official_email'), 'employees', ['official_email'], unique=True)
    op.create_table('role_skills',
    sa.Column('job_role_id', sa.UUID(), nullable=False, comment='FK reference to the JobRole'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='FK reference to the Skill'),
    sa.Column('required_proficiency', sa.Integer(), nullable=False, comment='Required proficiency level for the job role (1 to 5)'),
    sa.Column('mandatory', sa.Boolean(), nullable=False, comment='Indicates if the skill is mandatory for the job role'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint('required_proficiency >= 1 AND required_proficiency <= 5', name='chk_role_skills_proficiency_range'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_role_id', 'skill_id', name='uq_role_skills_job_role_skill')
    )
    op.create_index(op.f('ix_role_skills_job_role_id'), 'role_skills', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_role_skills_required_proficiency'), 'role_skills', ['required_proficiency'], unique=False)
    op.create_index(op.f('ix_role_skills_skill_id'), 'role_skills', ['skill_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='FK reference to the Employee who owns this document'),
    sa.Column('document_type', sa.Enum('RESUME', 'OFFER_LETTER', 'ONBOARDING', 'IDENTIFICATION', 'CONTRACT', 'OTHER', name='document_type'), nullable=False, comment='Type of document (e.g. RESUME, OFFER_LETTER)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Name of the file as uploaded'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='Storage path or URL of the document file'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type of the file (e.g. application/pdf, image/jpeg)'),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False, comment='FK reference to the User who uploaded the file'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the file was uploaded'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'file_path', name='uq_employee_documents_employee_filepath')
    )
    op.create_index(op.f('ix_employee_documents_employee_id'), 'employee_documents', ['employee_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='FK reference to the Employee'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='FK reference to the Skill'),
    sa.Column('proficiency_level', sa.Integer(), nullable=False, comment='Employee proficiency level in the skill (1 to 5)'),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=False, comment='Number of years of experience with the skill'),
    sa.Column('certification_status', sa.Boolean(), nullable=False, comment='Indicates whether the employee holds a certification for the skill'),
    sa.Column('last_assessed_date', sa.Date(), nullable=False, comment="Date when the employee's skill proficiency was last assessed"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint('proficiency_level >= 1 AND proficiency_level <= 5', name='chk_employee_skills_proficiency_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skills_employee_skill')
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_proficiency_level'), 'employee_skills', ['proficiency_level'], unique=False)
    op.create_index(op.f('ix_employee_skills_skill_id'), 'employee_skills', ['skill_id'], unique=False)
    op.create_table('performance_reviews',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='FK reference to the Employee being reviewed'),
    sa.Column('reviewer_id', sa.UUID(), nullable=False, comment='FK reference to the User performing the review'),
    sa.Column('review_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', name='review_cycle'), nullable=False, comment='Review cycle period type (e.g. MONTHLY, QUARTERLY, ANNUAL)'),
    sa.Column('review_period', sa.String(length=100), nullable=False, comment='Specific cycle string (e.g. Q1 2026, Mid-Year 2026)'),
    sa.Column('review_date', sa.Date(), nullable=False, comment='The date when the review was conducted'),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Calculated overall score percentage or numeric evaluation score'),
    sa.Column('overall_rating', sa.Integer(), nullable=False, comment='Overall rating score (1 to 5)'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='Written notes on employee strengths'),
    sa.Column('improvement_areas', sa.Text(), nullable=True, comment='Written notes on areas requiring development'),
    sa.Column('manager_comments', sa.Text(), nullable=True, comment='Additional comments or summary from the reviewer'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint('overall_rating >= 1 AND overall_rating <= 5', name='chk_performance_reviews_rating_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_reviews_employee_date', 'performance_reviews', ['employee_id', 'review_date'], unique=False)
    op.create_index(op.f('ix_performance_reviews_employee_id'), 'performance_reviews', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_reviews_overall_rating'), 'performance_reviews', ['overall_rating'], unique=False)
    op.create_index(op.f('ix_performance_reviews_review_date'), 'performance_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_performance_reviews_reviewer_id'), 'performance_reviews', ['reviewer_id'], unique=False)
    op.create_table('prediction_history',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='FK reference to the Employee for whom prediction is generated'),
    sa.Column('model_registry_id', sa.UUID(), nullable=False, comment='FK reference to the Model version used for inference'),
    sa.Column('prediction_type', sa.Enum('ATTRITION', 'PERFORMANCE', 'PROMOTION', 'TRAINING', name='prediction_type'), nullable=False, comment='Type of prediction cycle (e.g. ATTRITION, PERFORMANCE)'),
    sa.Column('prediction_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Numerical prediction score or probability percentage'),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Optional model confidence score for the prediction'),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False, comment='Categorical risk level (e.g., LOW, CRITICAL)'),
    sa.Column('prediction_result', sa.String(length=100), nullable=False, comment='Summary result string of the prediction (e.g., Retained, At-Risk)'),
    sa.Column('prediction_reason', sa.Text(), nullable=True, comment='Explanation or primary drivers for the prediction'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the prediction was generated'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_history_employee_id'), 'prediction_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_prediction_history_generated_at'), 'prediction_history', ['generated_at'], unique=False)
    op.create_index(op.f('ix_prediction_history_model_registry_id'), 'prediction_history', ['model_registry_id'], unique=False)
    op.create_index(op.f('ix_prediction_history_prediction_type'), 'prediction_history', ['prediction_type'], unique=False)
    op.create_index(op.f('ix_prediction_history_risk_level'), 'prediction_history', ['risk_level'], unique=False)
    op.create_table('training_enrollments',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='FK reference to the Employee enrolled'),
    sa.Column('training_course_id', sa.UUID(), nullable=False, comment='FK reference to the TrainingCourse enrolled in'),
    sa.Column('enrollment_date', sa.Date(), nullable=False, comment='Date when the employee enrolled in the course'),
    sa.Column('completion_date', sa.Date(), nullable=True, comment='Date when the employee completed the course'),
    sa.Column('enrollment_status', sa.Enum('ENROLLED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'DROPPED', name='enrollment_status'), nullable=False, comment='Current status of the course enrollment (e.g. ENROLLED, COMPLETED)'),
    sa.Column('completion_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Optional exam or completion score percentage'),
    sa.Column('certificate_issued', sa.Boolean(), nullable=False, comment='Indicates whether a completion certificate was issued'),
    sa.Column('feedback_rating', sa.Integer(), nullable=True, comment='Optional course satisfaction rating left by the employee (1 to 5)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint('feedback_rating IS NULL OR (feedback_rating >= 1 AND feedback_rating <= 5)', name='chk_training_enrollments_feedback_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_course_id'], ['training_courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'training_course_id', name='uq_training_enrollments_employee_course')
    )
    op.create_index(op.f('ix_training_enrollments_employee_id'), 'training_enrollments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_training_enrollments_enrollment_status'), 'training_enrollments', ['enrollment_status'], unique=False)
    op.create_index(op.f('ix_training_enrollments_training_course_id'), 'training_enrollments', ['training_course_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='FK reference to the Employee who receives this recommendation'),
    sa.Column('prediction_history_id', sa.UUID(), nullable=True, comment='Optional FK reference to the specific Attrition/Performance prediction that triggered this'),
    sa.Column('recommendation_type', sa.Enum('RETENTION', 'TRAINING', 'PROMOTION', 'SKILL_DEVELOPMENT', name='recommendation_type'), nullable=False, comment='Focus type of recommendation (e.g. TRAINING, RETENTION, PROMOTION)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short summary of the recommendation'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed action item and description'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority_level'), nullable=False, comment='Severity or urgency priority of the recommendation'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='recommendation_status'), nullable=False, comment='Lifecycle status of recommendation (e.g., PENDING, ACCEPTED, COMPLETED)'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when recommendation was generated'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when recommendation was resolved/completed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prediction_history_id'], ['prediction_history.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_employee_id'), 'recommendations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_recommendations_prediction_history_id'), 'recommendations', ['prediction_history_id'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_prediction_history_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_employee_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_training_enrollments_training_course_id'), table_name='training_enrollments')
    op.drop_index(op.f('ix_training_enrollments_enrollment_status'), table_name='training_enrollments')
    op.drop_index(op.f('ix_training_enrollments_employee_id'), table_name='training_enrollments')
    op.drop_table('training_enrollments')
    op.drop_index(op.f('ix_prediction_history_risk_level'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_prediction_type'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_model_registry_id'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_generated_at'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_employee_id'), table_name='prediction_history')
    op.drop_table('prediction_history')
    op.drop_index(op.f('ix_performance_reviews_reviewer_id'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_review_date'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_overall_rating'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_employee_id'), table_name='performance_reviews')
    op.drop_index('ix_performance_reviews_employee_date', table_name='performance_reviews')
    op.drop_table('performance_reviews')
    op.drop_index(op.f('ix_employee_skills_skill_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_proficiency_level'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_employee_documents_employee_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_role_skills_skill_id'), table_name='role_skills')
    op.drop_index(op.f('ix_role_skills_required_proficiency'), table_name='role_skills')
    op.drop_index(op.f('ix_role_skills_job_role_id'), table_name='role_skills')
    op.drop_table('role_skills')
    op.drop_index(op.f('ix_employees_official_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_job_role_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_job_roles_department_id'), table_name='job_roles')
    op.drop_index('ix_job_roles_department_grade', table_name='job_roles')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_training_skills_training_course_id'), table_name='training_skills')
    op.drop_index(op.f('ix_training_skills_skill_id'), table_name='training_skills')
    op.drop_table('training_skills')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_department_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at_audit'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_courses_course_code'), table_name='training_courses')
    op.drop_table('training_courses')
    op.drop_index(op.f('ix_skills_skill_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_model_registry_model_version'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_is_active'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_algorithm'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
