"""
Common database-mappable enums used across the application.
"""

from enum import Enum


class UserRole(str, Enum):
    """
    Defines administrative and operational user roles within the system.
    """

    HR_ADMIN = "HR_ADMIN"
    HR_MANAGER = "HR_MANAGER"
    EMPLOYEE = "EMPLOYEE"


class EmploymentStatus(str, Enum):
    """
    Defines the current employment state of an employee.
    """

    ACTIVE = "ACTIVE"
    TERMINATED = "TERMINATED"
    ON_LEAVE = "ON_LEAVE"
    SUSPENDED = "SUSPENDED"


class PredictionStatus(str, Enum):
    """
    Defines the status of a machine learning attrition prediction or pipeline run.
    """

    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RecommendationType(str, Enum):
    """
    Defines the focus of an HR retention or training recommendation.
    """

    RETENTION = "RETENTION"
    TRAINING = "TRAINING"
    PROMOTION = "PROMOTION"
    SKILL_DEVELOPMENT = "SKILL_DEVELOPMENT"


class TrainingStatus(str, Enum):
    """
    Defines the status of an employee's enrollment in a training course.
    """

    ENROLLED = "ENROLLED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Gender(str, Enum):
    """
    Defines the gender identity of an employee.
    """

    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"
    PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY"


class EmploymentType(str, Enum):
    """
    Defines the contract type of an employee.
    """

    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERN = "INTERN"


class WorkMode(str, Enum):
    """
    Defines where the employee performs their work.
    """

    OFFICE = "OFFICE"
    REMOTE = "REMOTE"
    HYBRID = "HYBRID"


class DocumentType(str, Enum):
    """
    Defines the type of employee documents uploaded to the system.
    """

    RESUME = "RESUME"
    OFFER_LETTER = "OFFER_LETTER"
    ONBOARDING = "ONBOARDING"
    IDENTIFICATION = "IDENTIFICATION"
    CONTRACT = "CONTRACT"
    OTHER = "OTHER"


class ReviewCycle(str, Enum):
    """
    Defines the frequency cycle of performance reviews.
    """

    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    HALF_YEARLY = "HALF_YEARLY"
    ANNUAL = "ANNUAL"


class TrainingMode(str, Enum):
    """
    Defines the instructional delivery format of a training course.
    """

    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    HYBRID = "HYBRID"


class DifficultyLevel(str, Enum):
    """
    Defines the level of prior knowledge required for a training course.
    """

    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"


class EnrollmentStatus(str, Enum):
    """
    Defines the progress status of a training course enrollment.
    """

    ENROLLED = "ENROLLED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    DROPPED = "DROPPED"


class PredictionType(str, Enum):
    """
    Defines the prediction types generated by machine learning models.
    """

    ATTRITION = "ATTRITION"
    PERFORMANCE = "PERFORMANCE"
    PROMOTION = "PROMOTION"
    TRAINING = "TRAINING"


class RiskLevel(str, Enum):
    """
    Defines the risk levels evaluated by machine learning models.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class PriorityLevel(str, Enum):
    """
    Defines the recommendation priority levels.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecommendationStatus(str, Enum):
    """
    Defines the status of a recommendation.
    """

    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"


class NotificationType(str, Enum):
    """
    Defines the type of a notification.
    """

    SYSTEM = "SYSTEM"
    ALERT = "ALERT"
    REMINDER = "REMINDER"
    AI_RECOMMENDATION = "AI_RECOMMENDATION"


class OvertimeFrequency(str, Enum):
    """
    Defines the frequency of overtime worked by an employee.
    """

    NONE = "NONE"
    OCCASIONAL = "OCCASIONAL"
    FREQUENT = "FREQUENT"
